### ISSUE TITLE
this doesnt work..

### ISSUE THREAD

**Issue by z1haze** [Asexual/agar.io-hacks#3]
it just loads  full grid on my screen with no buttons to play or anytihng.. justa blank grid

**Comment by ghost** [comment]
Same. There's an error in the console: `QUAD not defined`. [Line 218](https://github.com/Asexual/agar.io-hacks/blob/master/Agar.io%20cheatycodes%20-%20hacks.user.js#L218); does anyone know what is meant to happen?
